version: '3.9'
volumes:
  pg_data: { }
services:
  webapp:
    image: tabeldatadotcom/archetype:v1
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVFILE: .env.example
    environment:
      APP_PORT: 8080
    volumes:
      - source: .env.example
        target: /var/www/apps/.env.example
        type: bind
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

