version: '3.9'
services:
  webapp:
    image: tabeldatadotcom/archetype:v1
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVFILE: env.yaml
