version: '3.9'
volumes:
  pg_data: { }
services:
  webapp:
    image: tabeldatadotcom/archetype:v1
    profiles:
      - dev
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVFILE: .env.docker
    environment:
      APP_PORT: 8080
    volumes:
      - source: .env.docker
        target: /var/www/apps/.env
        type: bind
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    profiles:
      - migrate
    env_file:
      - .env
    volumes:
      - ./db/migration:/migration
    entrypoint: [ "migrate", "-path=/migration", "-database=postgres://example:example@postgres:5432/example?sslmode=disable&search_path=public" ]
    command: [ "up" ]
