POST {{hostname}}:{{port}}{{context-path}}/api/v1/employees/save
Content-Type: application/json

{
  "firstName": "Dimas",
  "lastName": "Maryanto",
  "salary": 100000,
  "hireDate": "2015-08-25T00:00:00Z",
  "commissionPct": 0.4
}

### Create new employees

GET {{hostname}}:{{port}}{{context-path}}/api/v1/employees/findBy/616092ca-6976-4dd4-94a8-6fa5e4ca9a8a
Content-Type: application/json

### Get employee by id
