### Create new employees
POST {{hostname}}:{{port}}{{context-path}}/api/v1/employees/save
Content-Type: application/json

{
  "firstName": "Dimas",
  "lastName": "Maryanto",
  "salary": 100000,
  "hireDate": "2015-08-25T00:00:00Z",
  "commissionPct": 0.4
}

### Get employee by id

GET {{hostname}}:{{port}}{{context-path}}/api/v1/employees/findBy/1
Content-Type: application/json
